### PR TITLE
Update Rekor v0.3.0 -> v0.12.2

### PR DESCRIPTION
**Pull request by bradbeck**
Signed-off-by: Brad Beck <bradley.beck@gmail.com>

### CODE REVIEW

**Review by rgreinho — DISMISSED** [review]
👍

**Comment by bradbeck** [comment]
Haven't been able to confirm yet that this solves the problem we have been seeing with https://github.com/buildsec/frsca

**Comment by mlieberman85** [comment]
Either way we should update.

**Review by mlieberman85 — APPROVED** [review]
LGTM

**Review by rgreinho — APPROVED** [review]
👍

**Pull request merged**
